FROM python:3.11-slim

WORKDIR /app

COPY Backend/requirements.txt /app/requirements.txt

RUN pip install -r /app/requirements.txt

COPY Backend /app

EXPOSE 5000

ENTRYPOINT [ "python" ]

CMD [ "/app/app.py" ]
